---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "loadrush-stuff-composer"
  namespace: "default"
  labels:
    app: "loadrush-stuff-composer"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "loadrush-stuff-composer"
  template:
    metadata:
      labels:
        app: "loadrush-stuff-composer"
    spec:
      containers:
        - name: "loadrush-stuff-composer"
          image: "chaoyangnz/loadrush-stuff-composer"
          env:
            - name: "LOADRUSH_BASE_URL"
              valueFrom:
                configMapKeyRef:
                  key: "LOADRUSH_BASE_URL"
                  name: "loadrush-stuff-composer-config"
            - name: "LOADRUSH_INFLUXDB_API"
              valueFrom:
                configMapKeyRef:
                  key: "LOADRUSH_INFLUXDB_API"
                  name: "loadrush-stuff-composer-config"
            - name: "LOADRUSH_INFLUXDB_TOKEN"
              valueFrom:
                configMapKeyRef:
                  key: "LOADRUSH_INFLUXDB_TOKEN"
                  name: "loadrush-stuff-composer-config"
            - name: "LOADRUSH_INFLUXDB_ORG"
              valueFrom:
                configMapKeyRef:
                  key: "LOADRUSH_INFLUXDB_ORG"
                  name: "loadrush-stuff-composer-config"
            - name: "LOADRUSH_VERBOSE_METRICS"
              valueFrom:
                configMapKeyRef:
                  key: "LOADRUSH_VERBOSE_METRICS"
                  name: "loadrush-stuff-composer-config"
            - name: "LOADRUSH_TEST_ID"
              valueFrom:
                configMapKeyRef:
                  key: "LOADRUSH_TEST_ID"
                  name: "loadrush-stuff-composer-config"
            - name: "COMPOSER_OAUTH_COOKIE"
              valueFrom:
                configMapKeyRef:
                  key: "COMPOSER_OAUTH_COOKIE"
                  name: "loadrush-stuff-composer-config"
            - name: "COMPOSER_OAUTH_CLIENT_ID"
              valueFrom:
                configMapKeyRef:
                  key: "COMPOSER_OAUTH_CLIENT_ID"
                  name: "loadrush-stuff-composer-config"
            - name: "COMPOSER_OAUTH_CLIENT_SECRET"
              valueFrom:
                configMapKeyRef:
                  key: "COMPOSER_OAUTH_CLIENT_SECRET"
                  name: "loadrush-stuff-composer-config"
            - name: "COMPOSER_OAUTH_REFRESH_TOKEN"
              valueFrom:
                configMapKeyRef:
                  key: "COMPOSER_OAUTH_REFRESH_TOKEN"
                  name: "loadrush-stuff-composer-config"
            - name: "COMPOSER_OAUTH_ENCRYPTION_KEY"
              valueFrom:
                configMapKeyRef:
                  key: "COMPOSER_OAUTH_ENCRYPTION_KEY"
                  name: "loadrush-stuff-composer-config"
            - name: "COMPOSER_USERS"
              valueFrom:
                configMapKeyRef:
                  key: "COMPOSER_USERS"
                  name: "loadrush-stuff-composer-config"
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 1
              memory: 1000Mi
