apiVersion: 1

datasources:
- name: timescaledb
  type: postgres
  url: timescaledb:5432
  database: loadrush
  user: postgres
  secureJsonData:
    password: password
  jsonData:
    sslmode: "disable"
    timescaledb: true
    postgresVersion: 1100
