version: "3.9"
services:
  timescaledb:
    container_name: timescaledb
    image: timescale/pg_prometheus:latest-pg11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loadrush
    volumes:
      - ./timescaledb/loadrush.sql:/docker-entrypoint-initdb.d/loadrush.sql
      - ./timescaledb/data:/var/lib/postgresql/data
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    links:
      - timescaledb
volumes:
  logvolume01: {}
