apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
    version: 2.0.0-alpha
  name: influxdb
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
        version: 2.0.0-alpha
    spec:
      containers:
        - image: quay.io/influxdb/influxdb:2.0.0-alpha
          imagePullPolicy: IfNotPresent
          name: influxdb
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
