apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
    version: 2.0.0-alpha
  name: influxdb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
      version: 2.0.0-alpha
  template:
    metadata:
      labels:
        app: influxdb
        version: 2.0.0-alpha
    spec:
      containers:
        - image: quay.io/influxdb/influxdb:2.0.0-alpha
          imagePullPolicy: IfNotPresent
          name: influxdb
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: "/root/.influxdbv2"
              name: influxdb
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: influxdb
          persistentVolumeClaim:
            claimName: influxdb
